#!/bin/bash
sudo /etc/init.d/redis-server start
cd dituhui
PIDFILE=./resque.pid BACKGROUND=yes QUEUE=* rake resque:work --trace
rake sunspot:solr:start
#rails s


#cd dituhui
#PIDFILE=./resque.pid BACKGROUND=yes QUEUE=* rake resque:work RAILS_ENV=test
#rake sunspot:solr:start RAILS_ENV=test
#rails s -e test
